// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/roulette.proto

package roulette

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на аутентификацию в комнате
type AuthenticateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRoomRequest) Reset() {
	*x = AuthenticateRoomRequest{}
	mi := &file_proto_roulette_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRoomRequest) ProtoMessage() {}

func (x *AuthenticateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roulette_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRoomRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_roulette_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRoomRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AuthenticateRoomRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Ответ на аутентификацию
type AuthenticateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRoomResponse) Reset() {
	*x = AuthenticateRoomResponse{}
	mi := &file_proto_roulette_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRoomResponse) ProtoMessage() {}

func (x *AuthenticateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roulette_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRoomResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_roulette_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthenticateRoomResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthenticateRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Запрос на получение истории
type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // JWT токен для авторизации
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_proto_roulette_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roulette_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_roulette_proto_rawDescGZIP(), []int{2}
}

func (x *GetHistoryRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetHistoryRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Ответ с историей
type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	History       []*RouletteNumber      `protobuf:"bytes,2,rep,name=history,proto3" json:"history,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_proto_roulette_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roulette_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_roulette_proto_rawDescGZIP(), []int{3}
}

func (x *GetHistoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetHistoryResponse) GetHistory() []*RouletteNumber {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *GetHistoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Запрос на сохранение числа
type SaveNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Number        *RouletteNumber        `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"` // JWT токен для авторизации
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveNumberRequest) Reset() {
	*x = SaveNumberRequest{}
	mi := &file_proto_roulette_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveNumberRequest) ProtoMessage() {}

func (x *SaveNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roulette_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveNumberRequest.ProtoReflect.Descriptor instead.
func (*SaveNumberRequest) Descriptor() ([]byte, []int) {
	return file_proto_roulette_proto_rawDescGZIP(), []int{4}
}

func (x *SaveNumberRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SaveNumberRequest) GetNumber() *RouletteNumber {
	if x != nil {
		return x.Number
	}
	return nil
}

func (x *SaveNumberRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Ответ на сохранение числа
type SaveNumberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Session       *RouletteSession       `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveNumberResponse) Reset() {
	*x = SaveNumberResponse{}
	mi := &file_proto_roulette_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveNumberResponse) ProtoMessage() {}

func (x *SaveNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roulette_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveNumberResponse.ProtoReflect.Descriptor instead.
func (*SaveNumberResponse) Descriptor() ([]byte, []int) {
	return file_proto_roulette_proto_rawDescGZIP(), []int{5}
}

func (x *SaveNumberResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveNumberResponse) GetSession() *RouletteSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *SaveNumberResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Запрос на обновление истории
type UpdateHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	History       []*RouletteNumber      `protobuf:"bytes,2,rep,name=history,proto3" json:"history,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"` // JWT токен для авторизации
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHistoryRequest) Reset() {
	*x = UpdateHistoryRequest{}
	mi := &file_proto_roulette_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHistoryRequest) ProtoMessage() {}

func (x *UpdateHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roulette_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHistoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_roulette_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateHistoryRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateHistoryRequest) GetHistory() []*RouletteNumber {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *UpdateHistoryRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Ответ на обновление истории
type UpdateHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Session       *RouletteSession       `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHistoryResponse) Reset() {
	*x = UpdateHistoryResponse{}
	mi := &file_proto_roulette_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHistoryResponse) ProtoMessage() {}

func (x *UpdateHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roulette_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHistoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_roulette_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateHistoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateHistoryResponse) GetSession() *RouletteSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *UpdateHistoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Запрос на получение всех сессий
type GetSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // JWT токен для авторизации (админ)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionsRequest) Reset() {
	*x = GetSessionsRequest{}
	mi := &file_proto_roulette_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionsRequest) ProtoMessage() {}

func (x *GetSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roulette_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionsRequest.ProtoReflect.Descriptor instead.
func (*GetSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_roulette_proto_rawDescGZIP(), []int{8}
}

func (x *GetSessionsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Ответ с сессиями
type GetSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Sessions      []*RouletteSession     `protobuf:"bytes,2,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionsResponse) Reset() {
	*x = GetSessionsResponse{}
	mi := &file_proto_roulette_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionsResponse) ProtoMessage() {}

func (x *GetSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roulette_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionsResponse.ProtoReflect.Descriptor instead.
func (*GetSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_roulette_proto_rawDescGZIP(), []int{9}
}

func (x *GetSessionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetSessionsResponse) GetSessions() []*RouletteSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *GetSessionsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Запрос на потоковую передачу чисел
type StreamNumbersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // JWT токен для авторизации
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamNumbersRequest) Reset() {
	*x = StreamNumbersRequest{}
	mi := &file_proto_roulette_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNumbersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNumbersRequest) ProtoMessage() {}

func (x *StreamNumbersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roulette_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamNumbersRequest.ProtoReflect.Descriptor instead.
func (*StreamNumbersRequest) Descriptor() ([]byte, []int) {
	return file_proto_roulette_proto_rawDescGZIP(), []int{10}
}

func (x *StreamNumbersRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StreamNumbersRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Поток чисел в реальном времени
type NumberStream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*NumberStream_NewNumber
	//	*NumberStream_HistoryUpdate
	//	*NumberStream_Error
	//	*NumberStream_Ping
	Event         isNumberStream_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberStream) Reset() {
	*x = NumberStream{}
	mi := &file_proto_roulette_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberStream) ProtoMessage() {}

func (x *NumberStream) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roulette_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberStream.ProtoReflect.Descriptor instead.
func (*NumberStream) Descriptor() ([]byte, []int) {
	return file_proto_roulette_proto_rawDescGZIP(), []int{11}
}

func (x *NumberStream) GetEvent() isNumberStream_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *NumberStream) GetNewNumber() *RouletteNumber {
	if x != nil {
		if x, ok := x.Event.(*NumberStream_NewNumber); ok {
			return x.NewNumber
		}
	}
	return nil
}

func (x *NumberStream) GetHistoryUpdate() *NumberHistoryUpdate {
	if x != nil {
		if x, ok := x.Event.(*NumberStream_HistoryUpdate); ok {
			return x.HistoryUpdate
		}
	}
	return nil
}

func (x *NumberStream) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Event.(*NumberStream_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *NumberStream) GetPing() *PingEvent {
	if x != nil {
		if x, ok := x.Event.(*NumberStream_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isNumberStream_Event interface {
	isNumberStream_Event()
}

type NumberStream_NewNumber struct {
	NewNumber *RouletteNumber `protobuf:"bytes,1,opt,name=new_number,json=newNumber,proto3,oneof"`
}

type NumberStream_HistoryUpdate struct {
	HistoryUpdate *NumberHistoryUpdate `protobuf:"bytes,2,opt,name=history_update,json=historyUpdate,proto3,oneof"`
}

type NumberStream_Error struct {
	Error *ErrorEvent `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type NumberStream_Ping struct {
	Ping *PingEvent `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

func (*NumberStream_NewNumber) isNumberStream_Event() {}

func (*NumberStream_HistoryUpdate) isNumberStream_Event() {}

func (*NumberStream_Error) isNumberStream_Event() {}

func (*NumberStream_Ping) isNumberStream_Event() {}

// Обновление истории чисел
type NumberHistoryUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*RouletteNumber      `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	FullSync      bool                   `protobuf:"varint,3,opt,name=full_sync,json=fullSync,proto3" json:"full_sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberHistoryUpdate) Reset() {
	*x = NumberHistoryUpdate{}
	mi := &file_proto_roulette_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberHistoryUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberHistoryUpdate) ProtoMessage() {}

func (x *NumberHistoryUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roulette_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberHistoryUpdate.ProtoReflect.Descriptor instead.
func (*NumberHistoryUpdate) Descriptor() ([]byte, []int) {
	return file_proto_roulette_proto_rawDescGZIP(), []int{12}
}

func (x *NumberHistoryUpdate) GetHistory() []*RouletteNumber {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *NumberHistoryUpdate) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *NumberHistoryUpdate) GetFullSync() bool {
	if x != nil {
		return x.FullSync
	}
	return false
}

// Событие ошибки
type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_proto_roulette_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roulette_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_proto_roulette_proto_rawDescGZIP(), []int{13}
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorEvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// Ping событие для поддержания соединения
type PingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingEvent) Reset() {
	*x = PingEvent{}
	mi := &file_proto_roulette_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingEvent) ProtoMessage() {}

func (x *PingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roulette_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingEvent.ProtoReflect.Descriptor instead.
func (*PingEvent) Descriptor() ([]byte, []int) {
	return file_proto_roulette_proto_rawDescGZIP(), []int{14}
}

func (x *PingEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Представление числа рулетки
type RouletteNumber struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*RouletteNumber_IntValue
	//	*RouletteNumber_StringValue
	Value         isRouletteNumber_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouletteNumber) Reset() {
	*x = RouletteNumber{}
	mi := &file_proto_roulette_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouletteNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouletteNumber) ProtoMessage() {}

func (x *RouletteNumber) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roulette_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouletteNumber.ProtoReflect.Descriptor instead.
func (*RouletteNumber) Descriptor() ([]byte, []int) {
	return file_proto_roulette_proto_rawDescGZIP(), []int{15}
}

func (x *RouletteNumber) GetValue() isRouletteNumber_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RouletteNumber) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*RouletteNumber_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *RouletteNumber) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*RouletteNumber_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

type isRouletteNumber_Value interface {
	isRouletteNumber_Value()
}

type RouletteNumber_IntValue struct {
	IntValue int32 `protobuf:"varint,1,opt,name=int_value,json=intValue,proto3,oneof"` // 0-36
}

type RouletteNumber_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"` // "00"
}

func (*RouletteNumber_IntValue) isRouletteNumber_Value() {}

func (*RouletteNumber_StringValue) isRouletteNumber_Value() {}

// Сессия рулетки
type RouletteSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	History       []*RouletteNumber      `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouletteSession) Reset() {
	*x = RouletteSession{}
	mi := &file_proto_roulette_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouletteSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouletteSession) ProtoMessage() {}

func (x *RouletteSession) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roulette_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouletteSession.ProtoReflect.Descriptor instead.
func (*RouletteSession) Descriptor() ([]byte, []int) {
	return file_proto_roulette_proto_rawDescGZIP(), []int{16}
}

func (x *RouletteSession) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RouletteSession) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RouletteSession) GetHistory() []*RouletteNumber {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *RouletteSession) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RouletteSession) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_proto_roulette_proto protoreflect.FileDescriptor

const file_proto_roulette_proto_rawDesc = "" +
	"\n" +
	"\x14proto/roulette.proto\x12\broulette\x1a\x1fgoogle/protobuf/timestamp.proto\"G\n" +
	"\x17AuthenticateRoomRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"d\n" +
	"\x18AuthenticateRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\";\n" +
	"\x11GetHistoryRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"|\n" +
	"\x12GetHistoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\ahistory\x18\x02 \x03(\v2\x18.roulette.RouletteNumberR\ahistory\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"m\n" +
	"\x11SaveNumberRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x06number\x18\x02 \x01(\v2\x18.roulette.RouletteNumberR\x06number\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"}\n" +
	"\x12SaveNumberResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x123\n" +
	"\asession\x18\x02 \x01(\v2\x19.roulette.RouletteSessionR\asession\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"r\n" +
	"\x14UpdateHistoryRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\ahistory\x18\x02 \x03(\v2\x18.roulette.RouletteNumberR\ahistory\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\x80\x01\n" +
	"\x15UpdateHistoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x123\n" +
	"\asession\x18\x02 \x01(\v2\x19.roulette.RouletteSessionR\asession\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"*\n" +
	"\x12GetSessionsRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x80\x01\n" +
	"\x13GetSessionsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x125\n" +
	"\bsessions\x18\x02 \x03(\v2\x19.roulette.RouletteSessionR\bsessions\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\">\n" +
	"\x14StreamNumbersRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\xf3\x01\n" +
	"\fNumberStream\x129\n" +
	"\n" +
	"new_number\x18\x01 \x01(\v2\x18.roulette.RouletteNumberH\x00R\tnewNumber\x12F\n" +
	"\x0ehistory_update\x18\x02 \x01(\v2\x1d.roulette.NumberHistoryUpdateH\x00R\rhistoryUpdate\x12,\n" +
	"\x05error\x18\x03 \x01(\v2\x14.roulette.ErrorEventH\x00R\x05error\x12)\n" +
	"\x04ping\x18\x04 \x01(\v2\x13.roulette.PingEventH\x00R\x04pingB\a\n" +
	"\x05event\"\x80\x01\n" +
	"\x13NumberHistoryUpdate\x122\n" +
	"\ahistory\x18\x01 \x03(\v2\x18.roulette.RouletteNumberR\ahistory\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x1b\n" +
	"\tfull_sync\x18\x03 \x01(\bR\bfullSync\":\n" +
	"\n" +
	"ErrorEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"E\n" +
	"\tPingEvent\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"]\n" +
	"\x0eRouletteNumber\x12\x1d\n" +
	"\tint_value\x18\x01 \x01(\x05H\x00R\bintValue\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValueB\a\n" +
	"\x05value\"\xdd\x01\n" +
	"\x0fRouletteSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x122\n" +
	"\ahistory\x18\x03 \x03(\v2\x18.roulette.RouletteNumberR\ahistory\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xe7\x03\n" +
	"\x0fRouletteService\x12Y\n" +
	"\x10AuthenticateRoom\x12!.roulette.AuthenticateRoomRequest\x1a\".roulette.AuthenticateRoomResponse\x12G\n" +
	"\n" +
	"GetHistory\x12\x1b.roulette.GetHistoryRequest\x1a\x1c.roulette.GetHistoryResponse\x12G\n" +
	"\n" +
	"SaveNumber\x12\x1b.roulette.SaveNumberRequest\x1a\x1c.roulette.SaveNumberResponse\x12P\n" +
	"\rUpdateHistory\x12\x1e.roulette.UpdateHistoryRequest\x1a\x1f.roulette.UpdateHistoryResponse\x12J\n" +
	"\vGetSessions\x12\x1c.roulette.GetSessionsRequest\x1a\x1d.roulette.GetSessionsResponse\x12I\n" +
	"\rStreamNumbers\x12\x1e.roulette.StreamNumbersRequest\x1a\x16.roulette.NumberStream0\x01B\x1fZ\x1dcasino-backend/proto/rouletteb\x06proto3"

var (
	file_proto_roulette_proto_rawDescOnce sync.Once
	file_proto_roulette_proto_rawDescData []byte
)

func file_proto_roulette_proto_rawDescGZIP() []byte {
	file_proto_roulette_proto_rawDescOnce.Do(func() {
		file_proto_roulette_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_roulette_proto_rawDesc), len(file_proto_roulette_proto_rawDesc)))
	})
	return file_proto_roulette_proto_rawDescData
}

var file_proto_roulette_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_roulette_proto_goTypes = []any{
	(*AuthenticateRoomRequest)(nil),  // 0: roulette.AuthenticateRoomRequest
	(*AuthenticateRoomResponse)(nil), // 1: roulette.AuthenticateRoomResponse
	(*GetHistoryRequest)(nil),        // 2: roulette.GetHistoryRequest
	(*GetHistoryResponse)(nil),       // 3: roulette.GetHistoryResponse
	(*SaveNumberRequest)(nil),        // 4: roulette.SaveNumberRequest
	(*SaveNumberResponse)(nil),       // 5: roulette.SaveNumberResponse
	(*UpdateHistoryRequest)(nil),     // 6: roulette.UpdateHistoryRequest
	(*UpdateHistoryResponse)(nil),    // 7: roulette.UpdateHistoryResponse
	(*GetSessionsRequest)(nil),       // 8: roulette.GetSessionsRequest
	(*GetSessionsResponse)(nil),      // 9: roulette.GetSessionsResponse
	(*StreamNumbersRequest)(nil),     // 10: roulette.StreamNumbersRequest
	(*NumberStream)(nil),             // 11: roulette.NumberStream
	(*NumberHistoryUpdate)(nil),      // 12: roulette.NumberHistoryUpdate
	(*ErrorEvent)(nil),               // 13: roulette.ErrorEvent
	(*PingEvent)(nil),                // 14: roulette.PingEvent
	(*RouletteNumber)(nil),           // 15: roulette.RouletteNumber
	(*RouletteSession)(nil),          // 16: roulette.RouletteSession
	(*timestamppb.Timestamp)(nil),    // 17: google.protobuf.Timestamp
}
var file_proto_roulette_proto_depIdxs = []int32{
	15, // 0: roulette.GetHistoryResponse.history:type_name -> roulette.RouletteNumber
	15, // 1: roulette.SaveNumberRequest.number:type_name -> roulette.RouletteNumber
	16, // 2: roulette.SaveNumberResponse.session:type_name -> roulette.RouletteSession
	15, // 3: roulette.UpdateHistoryRequest.history:type_name -> roulette.RouletteNumber
	16, // 4: roulette.UpdateHistoryResponse.session:type_name -> roulette.RouletteSession
	16, // 5: roulette.GetSessionsResponse.sessions:type_name -> roulette.RouletteSession
	15, // 6: roulette.NumberStream.new_number:type_name -> roulette.RouletteNumber
	12, // 7: roulette.NumberStream.history_update:type_name -> roulette.NumberHistoryUpdate
	13, // 8: roulette.NumberStream.error:type_name -> roulette.ErrorEvent
	14, // 9: roulette.NumberStream.ping:type_name -> roulette.PingEvent
	15, // 10: roulette.NumberHistoryUpdate.history:type_name -> roulette.RouletteNumber
	17, // 11: roulette.PingEvent.timestamp:type_name -> google.protobuf.Timestamp
	15, // 12: roulette.RouletteSession.history:type_name -> roulette.RouletteNumber
	17, // 13: roulette.RouletteSession.created_at:type_name -> google.protobuf.Timestamp
	17, // 14: roulette.RouletteSession.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 15: roulette.RouletteService.AuthenticateRoom:input_type -> roulette.AuthenticateRoomRequest
	2,  // 16: roulette.RouletteService.GetHistory:input_type -> roulette.GetHistoryRequest
	4,  // 17: roulette.RouletteService.SaveNumber:input_type -> roulette.SaveNumberRequest
	6,  // 18: roulette.RouletteService.UpdateHistory:input_type -> roulette.UpdateHistoryRequest
	8,  // 19: roulette.RouletteService.GetSessions:input_type -> roulette.GetSessionsRequest
	10, // 20: roulette.RouletteService.StreamNumbers:input_type -> roulette.StreamNumbersRequest
	1,  // 21: roulette.RouletteService.AuthenticateRoom:output_type -> roulette.AuthenticateRoomResponse
	3,  // 22: roulette.RouletteService.GetHistory:output_type -> roulette.GetHistoryResponse
	5,  // 23: roulette.RouletteService.SaveNumber:output_type -> roulette.SaveNumberResponse
	7,  // 24: roulette.RouletteService.UpdateHistory:output_type -> roulette.UpdateHistoryResponse
	9,  // 25: roulette.RouletteService.GetSessions:output_type -> roulette.GetSessionsResponse
	11, // 26: roulette.RouletteService.StreamNumbers:output_type -> roulette.NumberStream
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_roulette_proto_init() }
func file_proto_roulette_proto_init() {
	if File_proto_roulette_proto != nil {
		return
	}
	file_proto_roulette_proto_msgTypes[11].OneofWrappers = []any{
		(*NumberStream_NewNumber)(nil),
		(*NumberStream_HistoryUpdate)(nil),
		(*NumberStream_Error)(nil),
		(*NumberStream_Ping)(nil),
	}
	file_proto_roulette_proto_msgTypes[15].OneofWrappers = []any{
		(*RouletteNumber_IntValue)(nil),
		(*RouletteNumber_StringValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_roulette_proto_rawDesc), len(file_proto_roulette_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_roulette_proto_goTypes,
		DependencyIndexes: file_proto_roulette_proto_depIdxs,
		MessageInfos:      file_proto_roulette_proto_msgTypes,
	}.Build()
	File_proto_roulette_proto = out.File
	file_proto_roulette_proto_goTypes = nil
	file_proto_roulette_proto_depIdxs = nil
}
