// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/roulette.proto

package roulette

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RouletteService_AuthenticateRoom_FullMethodName = "/roulette.RouletteService/AuthenticateRoom"
	RouletteService_GetHistory_FullMethodName       = "/roulette.RouletteService/GetHistory"
	RouletteService_SaveNumber_FullMethodName       = "/roulette.RouletteService/SaveNumber"
	RouletteService_UpdateHistory_FullMethodName    = "/roulette.RouletteService/UpdateHistory"
	RouletteService_GetSessions_FullMethodName      = "/roulette.RouletteService/GetSessions"
	RouletteService_StreamNumbers_FullMethodName    = "/roulette.RouletteService/StreamNumbers"
)

// RouletteServiceClient is the client API for RouletteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис для работы с рулеткой через gRPC
type RouletteServiceClient interface {
	// Аутентификация в комнате
	AuthenticateRoom(ctx context.Context, in *AuthenticateRoomRequest, opts ...grpc.CallOption) (*AuthenticateRoomResponse, error)
	// Получить историю чисел
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
	// Сохранить новое число
	SaveNumber(ctx context.Context, in *SaveNumberRequest, opts ...grpc.CallOption) (*SaveNumberResponse, error)
	// Обновить историю чисел
	UpdateHistory(ctx context.Context, in *UpdateHistoryRequest, opts ...grpc.CallOption) (*UpdateHistoryResponse, error)
	// Получить все сессии
	GetSessions(ctx context.Context, in *GetSessionsRequest, opts ...grpc.CallOption) (*GetSessionsResponse, error)
	// Потоковая передача чисел в реальном времени
	StreamNumbers(ctx context.Context, in *StreamNumbersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NumberStream], error)
}

type rouletteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRouletteServiceClient(cc grpc.ClientConnInterface) RouletteServiceClient {
	return &rouletteServiceClient{cc}
}

func (c *rouletteServiceClient) AuthenticateRoom(ctx context.Context, in *AuthenticateRoomRequest, opts ...grpc.CallOption) (*AuthenticateRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticateRoomResponse)
	err := c.cc.Invoke(ctx, RouletteService_AuthenticateRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rouletteServiceClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryResponse)
	err := c.cc.Invoke(ctx, RouletteService_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rouletteServiceClient) SaveNumber(ctx context.Context, in *SaveNumberRequest, opts ...grpc.CallOption) (*SaveNumberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveNumberResponse)
	err := c.cc.Invoke(ctx, RouletteService_SaveNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rouletteServiceClient) UpdateHistory(ctx context.Context, in *UpdateHistoryRequest, opts ...grpc.CallOption) (*UpdateHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateHistoryResponse)
	err := c.cc.Invoke(ctx, RouletteService_UpdateHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rouletteServiceClient) GetSessions(ctx context.Context, in *GetSessionsRequest, opts ...grpc.CallOption) (*GetSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionsResponse)
	err := c.cc.Invoke(ctx, RouletteService_GetSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rouletteServiceClient) StreamNumbers(ctx context.Context, in *StreamNumbersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NumberStream], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RouletteService_ServiceDesc.Streams[0], RouletteService_StreamNumbers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamNumbersRequest, NumberStream]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RouletteService_StreamNumbersClient = grpc.ServerStreamingClient[NumberStream]

// RouletteServiceServer is the server API for RouletteService service.
// All implementations must embed UnimplementedRouletteServiceServer
// for forward compatibility.
//
// Сервис для работы с рулеткой через gRPC
type RouletteServiceServer interface {
	// Аутентификация в комнате
	AuthenticateRoom(context.Context, *AuthenticateRoomRequest) (*AuthenticateRoomResponse, error)
	// Получить историю чисел
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
	// Сохранить новое число
	SaveNumber(context.Context, *SaveNumberRequest) (*SaveNumberResponse, error)
	// Обновить историю чисел
	UpdateHistory(context.Context, *UpdateHistoryRequest) (*UpdateHistoryResponse, error)
	// Получить все сессии
	GetSessions(context.Context, *GetSessionsRequest) (*GetSessionsResponse, error)
	// Потоковая передача чисел в реальном времени
	StreamNumbers(*StreamNumbersRequest, grpc.ServerStreamingServer[NumberStream]) error
	mustEmbedUnimplementedRouletteServiceServer()
}

// UnimplementedRouletteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouletteServiceServer struct{}

func (UnimplementedRouletteServiceServer) AuthenticateRoom(context.Context, *AuthenticateRoomRequest) (*AuthenticateRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateRoom not implemented")
}
func (UnimplementedRouletteServiceServer) GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedRouletteServiceServer) SaveNumber(context.Context, *SaveNumberRequest) (*SaveNumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveNumber not implemented")
}
func (UnimplementedRouletteServiceServer) UpdateHistory(context.Context, *UpdateHistoryRequest) (*UpdateHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHistory not implemented")
}
func (UnimplementedRouletteServiceServer) GetSessions(context.Context, *GetSessionsRequest) (*GetSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessions not implemented")
}
func (UnimplementedRouletteServiceServer) StreamNumbers(*StreamNumbersRequest, grpc.ServerStreamingServer[NumberStream]) error {
	return status.Errorf(codes.Unimplemented, "method StreamNumbers not implemented")
}
func (UnimplementedRouletteServiceServer) mustEmbedUnimplementedRouletteServiceServer() {}
func (UnimplementedRouletteServiceServer) testEmbeddedByValue()                         {}

// UnsafeRouletteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouletteServiceServer will
// result in compilation errors.
type UnsafeRouletteServiceServer interface {
	mustEmbedUnimplementedRouletteServiceServer()
}

func RegisterRouletteServiceServer(s grpc.ServiceRegistrar, srv RouletteServiceServer) {
	// If the following call pancis, it indicates UnimplementedRouletteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RouletteService_ServiceDesc, srv)
}

func _RouletteService_AuthenticateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouletteServiceServer).AuthenticateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouletteService_AuthenticateRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouletteServiceServer).AuthenticateRoom(ctx, req.(*AuthenticateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouletteService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouletteServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouletteService_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouletteServiceServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouletteService_SaveNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouletteServiceServer).SaveNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouletteService_SaveNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouletteServiceServer).SaveNumber(ctx, req.(*SaveNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouletteService_UpdateHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouletteServiceServer).UpdateHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouletteService_UpdateHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouletteServiceServer).UpdateHistory(ctx, req.(*UpdateHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouletteService_GetSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouletteServiceServer).GetSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouletteService_GetSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouletteServiceServer).GetSessions(ctx, req.(*GetSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouletteService_StreamNumbers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamNumbersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RouletteServiceServer).StreamNumbers(m, &grpc.GenericServerStream[StreamNumbersRequest, NumberStream]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RouletteService_StreamNumbersServer = grpc.ServerStreamingServer[NumberStream]

// RouletteService_ServiceDesc is the grpc.ServiceDesc for RouletteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RouletteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "roulette.RouletteService",
	HandlerType: (*RouletteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthenticateRoom",
			Handler:    _RouletteService_AuthenticateRoom_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _RouletteService_GetHistory_Handler,
		},
		{
			MethodName: "SaveNumber",
			Handler:    _RouletteService_SaveNumber_Handler,
		},
		{
			MethodName: "UpdateHistory",
			Handler:    _RouletteService_UpdateHistory_Handler,
		},
		{
			MethodName: "GetSessions",
			Handler:    _RouletteService_GetSessions_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamNumbers",
			Handler:       _RouletteService_StreamNumbers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/roulette.proto",
}
